/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useCallback, useEffect, useState } from "react";

const initializeSequence = [
  "対話型制度探索社会最適化支援システム。",
  "オプティマイザー、起動しました。",
  "ユーザー認証。",
  "使用許諾確認。",
  "適正ユーザーです。",
  "支援モード、ゴールシーク・エクスプローラー。",
  "落ち着いて状況を整理し、困り事または悩み事を簡潔に入力してください。",
];

export default function Home() {
  const [responseTextList, setResponseTextList] = useState([""]);
  const [responseTextListLength, setResponseTextListLength] = useState(1);
  const [lastResponseTextLength, setLastResponseTextLength] = useState(0);

  const initializer = useCallback(() => {
    if (
      responseTextListLength === initializeSequence.length &&
      lastResponseTextLength ===
        initializeSequence[initializeSequence.length - 1].length
    ) {
      return;
    }
    let newResponseText = "";
    if (
      lastResponseTextLength <
      initializeSequence[responseTextListLength - 1].length
    ) {
      newResponseText = initializeSequence[responseTextListLength - 1].slice(
        0,
        lastResponseTextLength + 1
      );
    }

    let newResponseTextList = [""];
    if (responseTextListLength === 0) {
      newResponseTextList = [newResponseText];
    } else {
      newResponseTextList = [
        ...initializeSequence.slice(0, responseTextListLength - 1),
        newResponseText,
      ];
    }
    setResponseTextList(newResponseTextList);
    setResponseTextListLength(newResponseTextList.length);
    if (
      lastResponseTextLength <
      initializeSequence[responseTextListLength - 1].length
    ) {
      newResponseText = initializeSequence[responseTextListLength - 1].slice(
        0,
        lastResponseTextLength + 1
      );
      setResponseTextListLength(newResponseTextList.length);
      setLastResponseTextLength(newResponseText.length);
    } else {
      setResponseTextListLength(newResponseTextList.length + 1);
      setLastResponseTextLength(0);
    }
  }, [lastResponseTextLength, responseTextListLength]);

  useEffect(() => {
    setTimeout(initializer, 100);
  }, [initializer]);

  return (
    <>
      <Head>
        <title>対話型制度探索社会最適化支援システム オプティマイザー</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ width: "50vw" }}>
          {responseTextList.map((responseText, idx) => {
            return (
              <div
                key={idx}
                style={{
                  display: "flex",
                  marginBottom: "10px",
                  alignItems: "center",
                }}
              >
                <div style={{ marginRight: "10px" }}>
                  <img
                    width={20}
                    height={20}
                    src="https://i.gyazo.com/311db640f4fc0083ea572e6bb2e433d0.png"
                    alt="ai logo"
                  />
                </div>
                <div>
                  <h3>{responseText}</h3>
                </div>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
